name: Docker-Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "**"

jobs:
    docker-build:
        name: Docker Build
        runs-on: ubuntu-latest
        
        steps:

          - name: Check Docker Compose Version
            run: docker-compose version
    
          - name: Checkout Code
            uses: actions/checkout@v2

          - name: prepare env config
            run: |
                docker-compose -f "docker-compose.yml" build
            env:
                DOCKER_BUILDKIT: 0
